HitApp/Models/Contractor.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HitApp.Models
{
    public class Contractor
    {
        public int ContractorId { get; set; }

        [Display(Name = "Company")]
        public string ContractorCompany { get; set; }

        [Required]
        [Display(Name = "Contractor Name (Required)")]
        public string ContractorName { get; set; }        
        [Display(Name = "Email Address")]
        public string ContractorEmail { get; set; }
        [Display(Name = "Phone Number")]
        public string ContractorPhone { get; set; }
        [Display(Name = "Service")]
        public string ContractorService { get; set; }
        [Display(Name = "Website")]
        public string ContractorWebsiteUrl { get; set; }


        [Display(Name = "Address")]
        public string ContractorAddress { get; set; }        
        [Display(Name = "City")]
        public string ContractorCity { get; set; }
        [Display(Name = "State")]
        public string ContractorState { get; set; }
        [Display(Name = "Zip Code")]
        public int? ContractorZip { get; set; }

        [Display(Name = "Additional Notes")]
        public string ContractorAdditionalNotes { get; set; }

        [JsonIgnore]
        public virtual List<ProjectContractor> ProjectContractors { get; set; }
    }
}

HitApp/Controllers/Api/ContractorsController.cs
using HitApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HitApp.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class ContractorsController : ControllerBase
    {
        private IContractorRepository contractorRepo;
        private IProjectContractorRepository projectContractorRepo;

        public ContractorsController(IContractorRepository contractorRepo, IProjectContractorRepository projectContractorRepo)
        {
            this.contractorRepo = contractorRepo;
            this.projectContractorRepo = projectContractorRepo;

        }

        [HttpPost]
        public bool Delete(int id)
        {
            projectContractorRepo.Delete(id);
            return true;
        }

    } 
}

HitApp/Controllers/ContractorsController.cs
using HitApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HitApp.Controllers
{
    public class ContractorsController : Controller
    {
        private IContractorRepository contractorRepo;
        private IProjectRepository projectRepo;

        public ContractorsController(IContractorRepository contractorRepo, IProjectRepository projectRepo)
        {
            this.contractorRepo = contractorRepo;
            this.projectRepo = projectRepo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = contractorRepo.GetAll();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            var project = projectRepo.GetById(id);
            ViewBag.ProjectId = project.ProjectId;
            ViewBag.ProjectName = project.ProjectName;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contractor contractor, int id)
        {
            contractorRepo.Create(contractor);
            contractorRepo.LinkProjectIdToProjectContractor(contractor, id);

            return RedirectToAction("Details", "Projects", new { Id = id });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = contractorRepo.GetById(id);
            return View(model);
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeletePost(int id)
        {        
            contractorRepo.Delete(id);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = contractorRepo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Contractor contractor)
        {
            contractorRepo.Update(contractor);
            return RedirectToAction("Details" , new { Id = contractor.ContractorId });
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var model = contractorRepo.GetById(id);
            return View(model);
        }
    }
}

HitApp/Controllers/ProjectsController.cs
using HitApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

using Microsoft.AspNetCore.Http;
using System.IO;
using System;

namespace HitApp.Controllers
{
    public class ProjectsController : Controller
    {
        private IProjectRepository projectRepo;
        private IExpenseRepository expenseRepo;


        public ProjectsController(IProjectRepository projectRepo, IExpenseRepository expenseRepo)
        {
            this.projectRepo = projectRepo;
            this.expenseRepo = expenseRepo;
        }

        public IActionResult Index()
        {
            var model = projectRepo.GetAll();
            model = from project in model
                   where project.ProjectOwnerId == User.FindFirstValue(ClaimTypes.NameIdentifier) //must be true
                   orderby project.ProjectId // sorts by the date
                   select project;
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = projectRepo.GetById(id);            
            model.ProjectTotalExpenses = expenseRepo.ExpenseTotal(model);
            return View(model);
        }

        public IActionResult Create()
        {
            var project = projectRepo.SetTodaysDate();

            return View(project);
        }

        [HttpPost]
        public IActionResult Create(Project project)
        {
            project.ProjectOwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            projectRepo.Create(project);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var project = projectRepo.GetById(id);
            return View(project);
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            projectRepo.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var project = projectRepo.GetById(id);
            return View(project);
        }

        [HttpPost]
        public IActionResult Edit(Project project)
        {
            project.ProjectOwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            projectRepo.Update(project);
            return RedirectToAction("Details", new { id = project.ProjectId});
        }


    }
}

HitApp/Views/Contractors/Create.cshtml
@model HitApp.Models.Contractor

@{
    ViewData["Title"] = "Create";
}


@section Styling{
<link href="~/css/Creates.css" rel="stylesheet" />
<link href="~/css/Contractors.css" rel="stylesheet" />
}


<div class="create-bg">
    <div class="back" id="go-to">
        <a asp-controller="Projects" asp-action="Details" asp-route-id="@ViewBag.ProjectId">
            <input type="button" value="Back to @ViewBag.ProjectName" class="btn btn-default" />
        </a>
    </div>
    <div class="cards">
        <h2>Create New Contractor for @ViewBag.ProjectName</h2>




        <div class="row">
            <div class="col-md-4">
                <form id="contractors" class="page-form" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ContractorCompany" class="control-label"></label>
                        <input asp-for="ContractorCompany" class="form-control" />
                        <span asp-validation-for="ContractorCompany" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorName" class="control-label"></label>
                        <input asp-for="ContractorName" class="form-control" />
                        <span asp-validation-for="ContractorName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorService" class="control-label"></label>
                        <input asp-for="ContractorService" class="form-control" />
                        <span asp-validation-for="ContractorService" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorEmail" class="control-label"></label>
                        <input asp-for="ContractorEmail" class="form-control" />
                        <span asp-validation-for="ContractorEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorPhone" class="control-label"></label>
                        <input asp-for="ContractorPhone" class="form-control" />
                        <span asp-validation-for="ContractorPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorWebsiteUrl" class="control-label"></label>
                        <input asp-for="ContractorWebsiteUrl" class="form-control" />
                        <span asp-validation-for="ContractorWebsiteUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorAddress" class="control-label"></label>
                        <input asp-for="ContractorAddress" class="form-control" />
                        <span asp-validation-for="ContractorAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorCity" class="control-label"></label>
                        <input asp-for="ContractorCity" class="form-control" />
                        <span asp-validation-for="ContractorCity" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ContractorAdditionalNotes" class="control-label"></label>
                        <textarea id="add-info" asp-for="ContractorAdditionalNotes" class="form-control"></textarea>
                        <span asp-validation-for="ContractorAdditionalNotes" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorState" class="control-label"></label>
                        <input asp-for="ContractorState" class="form-control" />
                        <span asp-validation-for="ContractorState" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContractorZip" class="control-label"></label>
                        <input asp-for="ContractorZip" class="form-control" />
                        <span asp-validation-for="ContractorZip" class="text-danger"></span>
                    </div>
                    <div id="create-cont" class="form-group">
                        <input type="submit" value="CREATE" id="sub-btn" class="btn btn-default" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

HitApp/Views/Contractors/Delete.cshtml
@model HitApp.Models.Contractor

@{
    ViewData["Title"] = "Delete";
}
@section Styling{
    <link href="~/css/Contractors.css" rel="stylesheet" />
}

<div class="back-btn">
    <a asp-controller="Contractors" asp-action="Index">
        <input type="button" value="ALL CONTRACTORS" style="font-weight:bold" class="btn btn-default" />
    </a>
</div>


<div class="cards">
    <h2>Are you sure you want to delete @Model.ContractorName?</h2>

    <div class="buttons-del" >
       
            <form id="del-form" asp-controller="Contractors" asp-action="/Delete" asp-route-id="@Model.ContractorId">

                <input id="delete" type="submit" value="DELETE" style="font-weight:bold" class="btn btn-default" />
            </form>
            <a  asp-controller="Contractors" asp-action="Details" asp-route-id="@Model.ContractorId">
                <input type="button" value="NO" style="font-weight:bold" class="btn btn-default" />
            </a>      

    </div>
</div>

HitApp/Views/Contractors/Details.cshtml
@model HitApp.Models.Contractor

@{
    ViewData["Title"] = "Details";
}
@section Styling{
<link href="~/css/Contractors.css" rel="stylesheet" />
}
<div class="back" id="go-to">
    <a asp-controller="Contractors" asp-action="Index">
        <input type="button" value="GO TO CONTRACTORS" style="font-weight:bold" class="btn btn-default" />
    </a>
</div>
<div class="cards">
    <h2 id="title">@Model.ContractorName</h2>



    <div>
        <div class="d-contractor">
            <div>
                <dl id="contractor" class="dl-horizontal">
                    <dt class="d-row">
                        Company:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorCompany)
                    </dd>
                    <dt class="d-row">
                        Name:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorName)
                    </dd>
                    <dt class="d-row">
                        Service:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorService)
                    </dd>
                    <dt class="d-row">
                        Email:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorEmail)
                    </dd>
                    <dt class="d-row">
                        Phone:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorPhone)
                    </dd>
                    <dt class="d-row">
                        Website:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorWebsiteUrl)
                    </dd>
                    <dt class="d-row">
                        Address:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorAddress)
                    </dd>
                    <dt class="d-row">
                        City:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorCity)
                    </dd>
                    <dt class="d-row">
                        State:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorState)
                    </dd>
                    <dt class="d-row">
                        Zip Code:
                    </dt>
                    <dd class="d-row">
                        @Html.DisplayFor(model => model.ContractorZip)
                    </dd>
                    <dt class="d-row">
                        Additional Notes:
                    </dt>
                    <dd class="d-row" >
                        @Html.DisplayFor(model => model.ContractorAdditionalNotes)
                    </dd>
                </dl>
                <div class="icons">

                    <div class="back">
                        <a asp-action="Edit" asp-route-id="@Model.ContractorId">
                            <input type="button" value="EDIT" class="btn btn-default" />
                        </a>
                    </div>
                    <div class="back">
                        <a href="/Contractors/Delete/@Model.ContractorId">
                            <input type="button" value="DELETE" class="btn btn-default" />
                        </a>
                    </div>
                </div>
                </div>
                <div>
                    <div id="contractor">
                        <h3>Assigned Projects</h3>
                        <ul class="d-row">
                            @if (Model.ProjectContractors.Count == 0)
                            {
                                <li>Not assigned to any projects</li>
                            }
                            else
                            {
                                foreach (var project in Model.ProjectContractors)
                                {
                                    <li id="proj-cont"><a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Projects.ProjectId">@project.Projects.ProjectName</a></li>
                                }
                            }
                        </ul>

                    </div>

                </div>
            </div>

    </div>

</div>

HitApp/Views/Contractors/Edit.cshtml
@model HitApp.Models.Contractor

@{
    ViewData["Title"] = "Edit";
}
@section Styling{
<link href="~/css/Contractors.css" rel="stylesheet" />
<link href="~/css/Creates.css" rel="stylesheet" />
}


<div id="go-to-spread">

        <div class="back go-to">
        <a asp-controller="Contractors" asp-action="Index">
            <input type="button" value="ALL CONTRACTORS" style="font-weight:bold" class="btn btn-default" />
        </a>
    </div>
</div>
<div class="cards">
    <h2>Edit @Model.ContractorName</h2>




    <div class="row">
        <div class="col-md-4">
            <form id="contractors" class="page-form" asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ContractorId" />
                <div class="form-group">
                    <label asp-for="ContractorCompany" class="control-label"></label>
                    <input asp-for="ContractorCompany" class="form-control" />
                    <span asp-validation-for="ContractorCompany" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorName" class="control-label"></label>
                    <input asp-for="ContractorName" class="form-control" />
                    <span asp-validation-for="ContractorName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorService" class="control-label"></label>
                    <input asp-for="ContractorService" class="form-control" />
                    <span asp-validation-for="ContractorService" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorEmail" class="control-label"></label>
                    <input asp-for="ContractorEmail" class="form-control" />
                    <span asp-validation-for="ContractorEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorPhone" class="control-label"></label>
                    <input asp-for="ContractorPhone" class="form-control" />
                    <span asp-validation-for="ContractorPhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorWebsiteUrl" class="control-label"></label>
                    <input asp-for="ContractorWebsiteUrl" class="form-control" />
                    <span asp-validation-for="ContractorWebsiteUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorAddress" class="control-label"></label>
                    <input asp-for="ContractorAddress" class="form-control" />
                    <span asp-validation-for="ContractorAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorCity" class="control-label"></label>
                    <input asp-for="ContractorCity" class="form-control" />
                    <span asp-validation-for="ContractorCity" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ContractorAdditionalNotes" class="control-label"></label>
                    <textarea id="add-info" asp-for="ContractorAdditionalNotes" class="form-control"></textarea>
                    <span asp-validation-for="ContractorAdditionalNotes" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorState" class="control-label"></label>
                    <input asp-for="ContractorState" class="form-control" />
                    <span asp-validation-for="ContractorState" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ContractorZip" class="control-label"></label>
                    <input asp-for="ContractorZip" class="form-control" />
                    <span asp-validation-for="ContractorZip" class="text-danger"></span>
                </div>
                <div id="create-cont" class="form-group">
                    <input type="submit" value="SAVE" style="font-weight:bold" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>


</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HitApp/Views/Contractors/Index.cshtml
@model IEnumerable<HitApp.Models.Contractor>

    @{
    ViewData["Title"] = "Index";
    }
    @section Styling{
    <link href="~/css/Contractors.css" rel="stylesheet" />
    }
    <div class="back" id="go-to">
        <a asp-controller="Projects" asp-action="Index">
            <input type="button" value="GO TO MY PROJECTS" style="font-weight:bold" class="btn btn-default" />
        </a>
    </div>
    <div class="cards">
        <h2>All Contractors</h2>

        @*<p>
            <a asp-action="Create"><i class="far fa-plus-square"></i> Add New Contractor</a>
        </p>*@
        <table class="table" id="contractors">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Company
                    </th>
                    <th>
                        Service
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>
                        Additional Notes
                    </th>
                    <th id="edit-del">Edit | Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ContractorId" title="Details">
                            @Html.DisplayFor(modelItem => item.ContractorName)
                        </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContractorCompany)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContractorService)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContractorEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContractorPhone)
                    </td>

                    <td title="@Html.DisplayFor(modelItem => item.ContractorAdditionalNotes)" class="truncate">
                        @Html.DisplayFor(modelItem => item.ContractorAdditionalNotes)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ContractorId" title="Edit"><i class="fas fa-pencil-alt"></i></a>  |

                        <a href="/Contractors/Delete/@item.ContractorId" title="Delete"><i class="fas fa-times"></i></a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>