HitApp/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HitApp.Models
{
    public class Project
    {
        public int ProjectId { get; set; }        

        public string ProjectOwnerId { get; set; }

        [Display(Name = "Display On Dashboard")]
        [DefaultValue(false)]
        public bool ProjectIsOnDashboard { get; set; }

        [Display(Name="Project Name")]
        public string ProjectName { get; set; }

        [Display(Name="Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = false,
               DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime ProjectStartDate { get; set; }

        [Display(Name="End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = false,
               DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? ProjectEndDate { get; set; }

        [Display(Name="Project Description")]
        public string ProjectDescription { get; set; }

        [Display(Name="Total Budget")]
        [DisplayFormat(DataFormatString = "${0:#,0.00}", ApplyFormatInEditMode = false)]
        public double ProjectTotalBudget { get; set; }


        public virtual List<Expense> Expenses { get; set; }

        [Display(Name = "Total Expenses")]
        [DisplayFormat(DataFormatString = "${0:#,0.00}", ApplyFormatInEditMode = false)]
        public double ProjectTotalExpenses { get; set; }
 
        public virtual List<ProjectContractor> ProjectContractors { get; set; }

        public virtual ICollection<FilePath> FilePaths { get; set; }

    }
}

HitApp/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HitApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HitApp.Controllers
{
    public class ExpensesController : Controller
    {
        private IExpenseRepository expenseRepo;
        private IProjectRepository projectRepo;

        public ExpensesController(IExpenseRepository expenseRepo, IProjectRepository projectRepo)
        {
            this.expenseRepo = expenseRepo;
            this.projectRepo = projectRepo;

        }

        public IActionResult Create(int id)
        {
            var project = projectRepo.GetById(id);
            var model = expenseRepo.AssignProjectId(id);
            model.Project = project;
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Expense expense)
        {
            expenseRepo.Create(expense);

            var project = projectRepo.GetById(expense.ProjectId);            
            project.ProjectTotalExpenses = expenseRepo.ExpenseTotal(project);
            expenseRepo.Save();
            return RedirectToAction("Create");
        }

        public IActionResult Delete(int id)
        {
            var model = expenseRepo.GetById(id);
            return View(model);
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeleteExpense(int id)
        {
            var expense = expenseRepo.GetById(id);
            var projectId = expense.ProjectId;
            expenseRepo.Delete(id);


            var project = projectRepo.GetById(projectId);
            project.ProjectTotalExpenses = expenseRepo.ExpenseTotal(project);
            expenseRepo.Save();
            return RedirectToAction("Details", "Projects", new { Id = projectId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = expenseRepo.GetById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Expense expense)
        {

            expenseRepo.Update(expense);


            var project = projectRepo.GetById(expense.ProjectId);
            project.ProjectTotalExpenses = expenseRepo.ExpenseTotal(project);
            expenseRepo.Save();

            return RedirectToAction("Details", "Projects", new { Id = expense.ProjectId });
        }

        //[HttpGet]
        //public IActionResult ReturnToProject(int id)
        //{
        //    var expense = expenseRepo.GetById(id);
        //    var projectId = expense.ProjectId;
        //    return RedirectToAction("Details", "Projects", id = projectId);
            
        //}
    }
}

HitApp/Controllers/FilePathsController.cs
using HitApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HitApp.Controllers
{
    public class FilePathsController : Controller
    {
        private IFilePathRepository filePathRepo;
        private IProjectRepository projectRepo;
        private readonly IHostingEnvironment he;

        public FilePathsController(IProjectRepository projectRepo, IFilePathRepository filePathRepo, IHostingEnvironment e)
        {
            this.projectRepo = projectRepo;
            this.filePathRepo = filePathRepo;
            he = e;
        }

        public IActionResult ImageUpload(int id, IFormFile upload)
        {
            var project = projectRepo.GetById(id);
            if (upload != null && upload.Length > 0)
            {
                var photo = new FilePath
                {
                    FileName = Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName),
                    FileType = FileType.Photo
                };
                project.FilePaths = new List<FilePath>();
                project.FilePaths.Add(photo);
                string filePath = Path.Combine(he.WebRootPath + "/UserImages/" + photo.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {

                    upload.CopyTo(stream);


                }
                projectRepo.Save();
                var path = "/UserImages/" + photo.FileName;
                ViewBag.Image = path;
            }
            ViewBag.ProjectName = project.ProjectName;
            ViewBag.ProjectId = id;
            return View();
        }

        public IActionResult Details(int id)
        {
            var model = filePathRepo.GetById(id);
            model.Project.ProjectOwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(model);
        }

        public IActionResult Index(int id)
        {            
            var model = filePathRepo.GetAll();
            model = from filePath in model
                    where filePath.ProjectId == id //must be true  
                    where filePath.Project.ProjectOwnerId == User.FindFirstValue(ClaimTypes.NameIdentifier)
                    orderby filePath.ProjectId // sorts by the date
                    select filePath;
            ViewBag.ProjectId = id;
            var project = projectRepo.GetById(id);
            ViewBag.ProjectName = project.ProjectName;
            
            return View(model);
        }
    }
}

HitApp/Controllers/ProjectsController.cs
using HitApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

using Microsoft.AspNetCore.Http;
using System.IO;
using System;

namespace HitApp.Controllers
{
    public class ProjectsController : Controller
    {
        private IProjectRepository projectRepo;
        private IExpenseRepository expenseRepo;


        public ProjectsController(IProjectRepository projectRepo, IExpenseRepository expenseRepo)
        {
            this.projectRepo = projectRepo;
            this.expenseRepo = expenseRepo;
        }

        public IActionResult Index()
        {
            var model = projectRepo.GetAll();
            model = from project in model
                   where project.ProjectOwnerId == User.FindFirstValue(ClaimTypes.NameIdentifier) //must be true
                   orderby project.ProjectId // sorts by the date
                   select project;
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = projectRepo.GetById(id);            
            model.ProjectTotalExpenses = expenseRepo.ExpenseTotal(model);
            return View(model);
        }

        public IActionResult Create()
        {
            var project = projectRepo.SetTodaysDate();

            return View(project);
        }

        [HttpPost]
        public IActionResult Create(Project project)
        {
            project.ProjectOwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            projectRepo.Create(project);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var project = projectRepo.GetById(id);
            return View(project);
        }

        [ActionName("Delete")]
        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            projectRepo.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var project = projectRepo.GetById(id);
            return View(project);
        }

        [HttpPost]
        public IActionResult Edit(Project project)
        {
            project.ProjectOwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            projectRepo.Update(project);
            return RedirectToAction("Details", new { id = project.ProjectId});
        }


    }
}

HitApp/Views/Projects/Create.cshtml
@model HitApp.Models.Project

@{
    ViewData["Title"] = "Create";
}
@section Styling{
    <link href="~/css/Creates.css" rel="stylesheet" />
    <link href="~/css/Projects.css" rel="stylesheet" />
}
<body id="ProjectIndex">

    <div class="back" id="go-to">
        <a asp-controller="Projects" asp-action="Index">
            <input type="button" value="BACK TO MY PROJECTS" class="btn btn-default" />
        </a>
    </div>
    <div class="cards">
        <h2>Create A New Project</h2>



        <div class="row">
            <div class="col-md-4">
                <form class="page-form" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="ProjectName" class="control-label"></label>
                        <input asp-for="ProjectName" class="form-control" />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectTotalBudget" class="control-label"></label>
                        <input asp-for="ProjectTotalBudget" class="form-control" />
                        <span asp-validation-for="ProjectTotalBudget" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectIsOnDashboard" class="control-label"></label>
                        <input type="checkbox" asp-for="ProjectIsOnDashboard" />
                        <span asp-validation-for="ProjectIsOnDashboard" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProjectStartDate" class="control-label"></label>
                        <input asp-for="ProjectStartDate" class="form-control" />
                        <span asp-validation-for="ProjectStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectEndDate" class="control-label"></label>
                        <input asp-for="ProjectEndDate" class="form-control" />
                        <span asp-validation-for="ProjectEndDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProjectDescription" class="control-label"></label>
                        <textarea id="add-info" asp-for="ProjectDescription" class="form-control"></textarea>
                        <span asp-validation-for="ProjectDescription" class="text-danger"></span>
                    </div>

                    <div id="create-proj" class="form-group">
                        <input style="font-weight:bold;" type="submit" value="CREATE" class="btn btn-default" />

                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HitApp/Views/Projects/Delete.cshtml
@model HitApp.Models.Project

@{
    ViewData["Title"] = "Delete";
}
@section Styling{
    <link href="~/css/Projects.css" rel="stylesheet" />
}
    <body id="ProjectIndex">
        <div class="cards">
            <h2>Are you sure you want to delete your @Model.ProjectName project?</h2>



            <div class="buttons-del">

                <form id="del-form" asp-action="Delete" asp-route-id="@Model.ProjectId">

                    <input id="delete" type="submit" value="DELETE" style="font-weight:bold" class="btn btn-default" />
                </form>
                <a asp-action="Details" asp-route-id="@Model.ProjectId" >
                    <input type="button" value="NO" style="font-weight:bold" class="btn btn-default" />
                </a>

            </div>
        </div>
</body>

HitApp/Views/Projects/Details.cshtml
@model HitApp.Models.Project

@{
    ViewData["Title"] = "Details";
}

@section Styling{
    <link href="~/css/Projects.css" rel="stylesheet" />
}
<body id="ProjectDetails">
    <div style="margin-top:20px" class="back">
        <a asp-action="Index">
            <input type="button" value="GO TO MY PROJECTS" class="btn btn-default" />
        </a>
    </div>
    <div id="Project">

        <div class="project-info">
            <h2 style="font-weight:bold">@Model.ProjectName Project Details</h2>

            <dl class="dl-horizontal">
                <dt> On Dashboard  </dt>
                @if (Model.ProjectIsOnDashboard == true)
                {
                    <dd><i id="green" class="fas fa-check"></i> </dd>
                }
                else
                {
                    <dd><i id="red" class="fas fa-ban"></i> </dd>
                }
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectStartDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectStartDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectEndDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectEndDate)
                </dd>
                <dt>
                    Description
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectDescription)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProjectTotalBudget)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProjectTotalBudget)
                </dd>
            </dl>
            <div class="icons">
                <div class="back">
                    <a asp-action="Edit" asp-route-id="@Model.ProjectId">
                        <input type="button" value="EDIT" class="btn btn-default" />
                    </a>
                </div>
                <div class="back">
                    <a asp-action="Delete" asp-route-id="@Model.ProjectId">
                        <input type="button" value="DELETE" class="btn btn-default" />
                    </a>
                </div>
            </div>
        </div>


        <div class="image-upload">
            <h2>Upload Images</h2>
            <div>
                <form method="post" action="/FilePaths/ImageUpload/@Model.ProjectId" enctype="multipart/form-data">
                    <input type="file" name="upload" /><br />
                    <input type="submit" value="UPLOAD" class="btn btn-default" />
                </form>
            </div>
            <div class="back">
                <a asp-controller="FilePaths" asp-action="Index" asp-route-id="@Model.ProjectId">
                    <input type="button" value="VIEW IMAGES" class="btn btn-default" />
                </a>
            </div>
        </div>




    </div>

    <div id="Contractors">
        <div id="cont-btns">
            <h3 style="font-weight:bold;">Contractors</h3>

            <div class="back">
                <a asp-controller="Contractors" asp-action="Create" asp-route-id="@Model.ProjectId">
                    <input type="button" value="CREATE CONTRACTOR" class="btn btn-default" />
                </a>
            </div>

        </div>

        <div id="contractor-table-header">
            <table class="table">
                <thead>
                    <tr class="contractor-table-header">
                        <th>
                            Name
                        </th>
                        <th>
                            Company
                        </th>
                        <th>
                            Service
                        </th>
                        <th>
                            Phone
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Notes
                        </th>
                        <th>Edit | Delete</th>
                    </tr>
                </thead>
                <tbody class="contractor-list">
                    @foreach (var item in Model.ProjectContractors)
                    {

                        <tr data-project-contractor-id="@item.ProjectContractorId">
                            <td>
                                <a asp-controller="Contractors" asp-action="Details" asp-route-id="@item.Contractors.ContractorId">@Html.DisplayFor(modelItem => item.Contractors.ContractorName)</a>

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contractors.ContractorCompany)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contractors.ContractorService)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contractors.ContractorPhone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Contractors.ContractorEmail)
                            </td>
                            <td title="@Html.DisplayFor(modelItem => item.Contractors.ContractorAdditionalNotes)" class="truncate">
                                @Html.DisplayFor(modelItem => item.Contractors.ContractorAdditionalNotes)
                            </td>


                            <td class="edit-del">

                                <a asp-controller="Contractors" asp-action="Edit" asp-route-id="@item.Contractors.ContractorId"><i class="fas fa-pencil-alt"></i></a> |
                                <a class="remove-contractor" data-project-contractor-id="@item.ProjectContractorId"><i class="fas fa-times"></i></a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="back" id="back">
                <a asp-controller="Contractors" asp-action="Index" asp-route-id="@Model.ProjectId">
                    <input type="button" value="ALL CONTRACTORS" class="btn btn-default" />
                </a>
            </div>
        </div>
    </div>


    <div id="ExpenseTable">
        <div id="exp-top">
            <h3 style="font-weight:bold;">Expenses</h3>

            <div class="back">
                <a asp-controller="Expenses" asp-action="Create" asp-route-id="@Model.ProjectId">
                    <input type="button" value="CREATE EXPENSE" class="btn btn-default" />
                </a>
            </div>



        </div>
        <table class="table">
            <thead>
                <tr class="expense-table-header">
                    <th>
                        Name
                    </th>
                    <th>
                        Product Link
                    </th>
                    <th>
                        Date Purchased
                    </th>
                    <th>
                        Notes
                    </th>
                    <th id="expense-cost">
                        Total Cost
                    </th>
                    <th>Edit | Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Expenses)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpenseName)
                        </td>
                        <td>
                            @if (item.ProductUrl == null || item.ProductUrl == "https://")
                            {
                                //nothing will be displayed
                            }
                            else
                            {
                                <a href="@Html.DisplayFor(modelItem => item.ProductUrl)" target="_blank">
                                    @Html.DisplayFor(modelItem => item.ExpenseName)
                                </a>

                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ExpenseDatePurchased)
                        </td>

                        <td title="@Html.DisplayFor(modelItem => item.ExpenseNotes)" class="truncate">
                            @Html.DisplayFor(modelItem => item.ExpenseNotes)
                        </td>
                        <td id="expense-cost">
                            @Html.DisplayFor(modelItem => item.ExpenseCost)
                        </td>
                        <td class="edit-del">
                            <a asp-controller="Expenses" asp-action="Edit" asp-route-id="@item.ExpenseId" title="Edit"><i class="fas fa-pencil-alt"></i>  </a> |
                            <a asp-controller="Expenses" asp-action="Delete" asp-route-id="@item.ExpenseId" title="Delete"><i class="fas fa-times"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h3 id="tot-exp">@Html.DisplayFor(model => model.ProjectTotalExpenses) = Total Expenses</h3>
    </div>

</body>

@section Scripts{
    <script src="~/js/Contractors.js"></script>
}

HitApp/Views/Projects/Edit.cshtml
@model HitApp.Models.Project

@{
    ViewData["Title"] = "Edit";
}

@section Styling{
    <link href="~/css/Creates.css" rel="stylesheet" />
    <link href="~/css/Projects.css" rel="stylesheet" />
}
<body id="ProjectIndex">
    <div class="back" id="go-to">
        <a asp-controller="Projects" asp-action="Details" asp-route-id="@Model.ProjectId">
            <input type="button" value="Back to @Model.ProjectName" class="btn btn-default" />
        </a>
    </div>
    <div class="cards">

        <h2>Edit @Model.ProjectName Project</h2>


        <div class="row">
            <div class="col-md-4">
                <form class="page-form" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ProjectId" />
                    <div class="form-group">
                        <label asp-for="ProjectName" class="control-label"></label>
                        <input asp-for="ProjectName" class="form-control" />
                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectTotalBudget" class="control-label"></label>
                        <input asp-for="ProjectTotalBudget" class="form-control" />
                        <span asp-validation-for="ProjectTotalBudget" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectIsOnDashboard" class="control-label"></label>
                        <input type="checkbox" asp-for="ProjectIsOnDashboard" />
                        <span asp-validation-for="ProjectIsOnDashboard" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProjectStartDate" class="control-label"></label>
                        <input asp-for="ProjectStartDate" class="form-control" />
                        <span asp-validation-for="ProjectStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProjectEndDate" class="control-label"></label>
                        <input asp-for="ProjectEndDate" class="form-control" />
                        <span asp-validation-for="ProjectEndDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProjectDescription" class="control-label"></label>
                        <textarea id="add-info" asp-for="ProjectDescription" class="form-control"></textarea>
                        <span asp-validation-for="ProjectDescription" class="text-danger"></span>
                    </div>
                    <div id="create-proj" class="form-group">
                        <input type="submit" value="SAVE" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HitApp/Views/Projects/Index.cshtml
@model IEnumerable<HitApp.Models.Project>

@{
    ViewData["Title"] = "Index";
}




@section Styling{
    <link href="~/css/Projects.css" rel="stylesheet" />
}
<body id="ProjectIndex">
    <div class="back" id="go-to">
        <a asp-controller="Contractors" asp-action="Index">
            <input type="button" value="GO TO CONTRACTORS" class="btn btn-default" />
        </a>
    </div>
    <div class="cards">
        <div class="proj-btns">
            <h2>My Projects</h2>

            <div class="back">
                <a asp-controller="Projects" asp-action="Create">
                    <input type="button" value="CREATE PROJECT" class="btn btn-default" />
                </a>
            </div>


        </div>
        <table id="tableId" class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ProjectName)

                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProjectDescription)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProjectStartDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProjectEndDate)
                    </th>
                    <th>
                        On Dashboard
                    </th>

                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>

                            <a asp-action="Details" asp-route-id="@item.ProjectId" title="Details">@Html.DisplayFor(modelItem => item.ProjectName)</a>


                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProjectDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProjectStartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProjectEndDate)
                        </td>
                        @if (item.ProjectIsOnDashboard == true)
                        {
                            <td><i id="cant-change" class="fas fa-check"></i></td>
                        }
                        else
                        {
                            <td><i id="cant-change" class="fas fa-ban"></i></td>
                        }

                        <td>

                            <a asp-action="Delete" asp-route-id="@item.ProjectId" title="Delete"><i class="fas fa-times icon-center"></i></a>
                        </td>
                    </tr>
                }

            </tbody>



        </table>

    </div>

</body>